jobs:
  - name: ConvertSegmentsJob
    class: ConvertSegmentsJob
    params:
      job_type: create_table
      table: your_table_name
      jar_path: your_jar_path
      kafka_required_fields: []
      module: your_module
      domain: your_domain
      custom_schema_model_file: your_custom_schema_model_file
      custom_table_config_file: your_custom_table_config_file
      kafka_schemaregistry_topic: your_kafka_schemaregistry_topic
  - name: ConvertSegmentsJob
    class: ConvertSegmentsJob
    params:
      job_type: convert_segments
      table: your_table_name
      jar_path: your_jar_path
  - name: ConvertSegmentsJob
    class: ConvertSegmentsJob
    params:
      job_type: convert_all_segments
      jar_path: your_jar_path

dags:
  - name: convert_segments_dag
    schedule_interval: "@daily"
    tasks:
      - name: create_table
        job: ConvertSegmentsJob
        params:
          job_type: create_table
          table: your_table_name
          kafka_required_fields: []
          module: your_module
          domain: your_domain
          custom_schema_model_file: your_custom_schema_model_file
          custom_table_config_file: your_custom_table_config_file
          kafka_schemaregistry_topic: your_kafka_schemaregistry_topic
      - name: convert_segments
        job: ConvertSegmentsJob
        params:
          job_type: convert_segments
          table: your_table_name
          jar_path: your_jar_path
      - name: convert_all_segments
        job: ConvertSegmentsJob
        params:
          job_type: convert_all_segments
          jar_path: your_jar_path
