variables:
  PYTHON_VERSION_CICD: "3.9"

include:
  - project: "Plataformas/pipelines/cicd"
    ref: master
    file: "interlake/bundle/nexus-wheel-v2/.gitlab-ci.yml"

# Defina os estágios necessários se não estiverem no arquivo incluído
stages:
  - .pre
  - build
  - .post

# Adicione aqui as etapas específicas se necessário
before_script:
  - pip install --upgrade pip poetry

# Job para build, caso precise de personalização adicional
build:
  stage: build
  script:
    - poetry install
    - poetry build
  artifacts:
    paths:
      - dist/
