variables:
  PYTHON_VERSION_CICD: "3.9"

include:
  - project: "Plataformas/pipelines/cicd"
    ref: master
    file: "interlake/bundle/nexus-wheel-v2/.gitlab-ci.yml"

# Caso precise adicionar mais configurações específicas, pode incluir abaixo
stages:
  - build

# Definindo uma variável para o cache do pip
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Etapas antes do script principal
before_script:
  - pip install --upgrade pip poetry

# Job para build
build:
  stage: build
  script:
    - poetry install
    - poetry build
  artifacts:
    paths:
      - dist/
